### PR TITLE
Revert "Remove composer dependencies from source code"

### PR DESCRIPTION
**Pull request by texxasrulez**
Reverts texxasrulez/caldav_calendar_te#64

This made my calendar unusable ...

### CODE REVIEW

**Comment by texxasrulez** [comment]
Here is my log from event. 

```
[24-Feb-2020 21:23:44 America/Phoenix] PHP Warning:  require_once(/var/www/path_to_roundcube/plugins/calendar/lib/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/path_to_roundcube/plugins/calendar/lib/caldav-client.php on line 25
[24-Feb-2020 21:23:44 America/Phoenix] PHP Fatal error:  require_once(): Failed opening required '/var/www/path_to_roundcube/plugins/calendar/lib/../vendor/autoload.php' (include_path='/var/www/path_to_roundcube/plugins/libkolab/lib:/var/www/path_to_roundcube/vendor/pear/auth_sasl:/var/www/path_to_roundcube/vendor/pear/console_commandline:/var/www/path_to_roundcube/vendor/pear/console_getopt:/var/www/path_to_roundcube/vendor/pear/crypt_gpg:/var/www/path_to_roundcube/vendor/pear/mail_mime:/var/www/path_to_roundcube/vendor/pear/net_idna2:/var/www/path_to_roundcube/vendor/pear/net_ldap2:/var/www/path_to_roundcube/vendor/pear/net_smtp:/var/www/path_to_roundcube/vendor/pear/net_socket:/var/www/path_to_roundcube/vendor/pear/pear-core-minimal/src:/var/www/path_to_roundcube/vendor/pear/pear_exception:/var/www/path_to_roundcube/program/lib: in /var/www/path_to_roundcube/plugins/calendar/lib/caldav-client.php on line 25
```


I am working on something else, or I would help out a bit on this. I know composer does not work but I was waiting to get this calendar working perfectly and then work on that. Most ppl cannot use composer anyway, so I placed this low on my list. I am not diminishing your work. I do appreciate it and I will incorporate this when I have a little more time to see why errors thrown on me ...

**Comment by LukasK32** [comment]
Did you use `composer install`?

> Navigate to /roundcube_directory/plugins/calendar and run `composer install`

I think that this is essential for this calendar to work perfectly :) When it is production ready, we could distribute version with composer already ran, like Roundcube itself does with its "complete" version for non-cli users.

**Comment by texxasrulez** [comment]
No, I am not ready for composer install. I am in the middle of another MAJOR update to this repo and my code is way different than yours. I am not going to worry about composer until I am satisfied with results .... I am close, be a little patient with me ... We will get there

**Comment by LukasK32** [comment]
I think that composer should be a top priority. It would make refactorization possible - code could be broken up into smaller, testable classes, which in turn would make development and collaboration with others (like us) easier.  Right now every change needs to be manually checked making it really hard and time consuming to fix already existing bugs. Adding more code on top of that will only make it worse I’m afraid.

Regarding your "MAJOR" update – I do not see any changes meaning we unfortunately cannot offer any help or contribute to it, let alone testing it with composer.

If you need any additional explanation please let me know and we will be more than happy to help. We really want to help with getting this plugin up and running so it could be used by broader audience :)

**Comment by pafcioooo** [comment]
@texxasrulez, this is great what @LukasK32 has written about composer. It would be definitely much easier, and huge waaaaaay faster to publish updates and allow other to collaborate :-) Cheers :-)

**Comment by texxasrulez** [comment]
As I have stated in previous requests. I will work on that as soon as I get my vision going. I personally don't use composer install methods and many newbies don't know how to do that but uploading and editing a file or two is easier. Rest assured, this is on the list, but not now for me ...

**Pull request closed without merging**
